// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: like.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO likes (
    "senderID", "receiverID"
) VALUES (
  $1, $2
)
RETURNING id, "senderID", "receiverID", created_at
`

type CreateUserParams struct {
	SenderID   pgtype.UUID `json:"senderID"`
	ReceiverID pgtype.UUID `json:"receiverID"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Like, error) {
	row := q.db.QueryRow(ctx, createUser, arg.SenderID, arg.ReceiverID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.CreatedAt,
	)
	return i, err
}
