// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Like struct {
	ID         pgtype.UUID        `json:"id"`
	SenderID   pgtype.UUID        `json:"senderID"`
	ReceiverID pgtype.UUID        `json:"receiverID"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	ID        pgtype.UUID        `json:"id"`
	User1ID   pgtype.UUID        `json:"user1ID"`
	User2ID   pgtype.UUID        `json:"user2ID"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID         pgtype.UUID        `json:"id"`
	SenderID   pgtype.UUID        `json:"senderID"`
	ReceiverID pgtype.UUID        `json:"receiverID"`
	Content    pgtype.Text        `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Password    string             `json:"password"`
	Gender      string             `json:"gender"`
	University  string             `json:"university"`
	Picture     []byte             `json:"picture"`
	Bio         string             `json:"bio"`
	BioPictures []string           `json:"bio_pictures"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
